name: Flutter Build (iOS and Android)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # Your Flutter version
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies (iOS)
        working-directory: ios
        run: |
          pod install

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android AAB
        run: flutter build appbundle --release

      - name: Build iOS (Simulator)
        run: flutter build ios --no-codesign

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload iOS Build (no IPA)
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
